"""To-event-Migration make project_id unique

Revision ID: 012d6b7a94e6
Revises: fd1edca75910
Create Date: 2025-04-04 07:47:15.320963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012d6b7a94e6'
down_revision: Union[str, None] = 'fd1edca75910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    op.alter_column('to_event_inventory', 'project_barcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('to_event_inventory', 'project_barcode_unique_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'to_event_inventory', ['project_id'])
    op.create_unique_constraint(None, 'to_event_inventory', ['project_barcode_image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'to_event_inventory', type_='unique')
    op.drop_constraint(None, 'to_event_inventory', type_='unique')
    op.alter_column('to_event_inventory', 'project_barcode_unique_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('to_event_inventory', 'project_barcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=True)
    # ### end Alembic commands ###
