"""correct_multi_row_input item id uuid

Revision ID: 1ce2d01f7d54
Revises: c156a41ac48f
Create Date: 2025-04-06 01:29:59.111891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce2d01f7d54'
down_revision: Union[str, None] = 'c156a41ac48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index(op.f('ix_entry_inventory_inventory_id'), 'entry_inventory', ['inventory_id'], unique=True)
    op.create_unique_constraint(None, 'inventory_items', ['id'])
    op.create_unique_constraint(None, 'to_event_inventory', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'to_event_inventory', type_='unique')
    op.drop_constraint(None, 'inventory_items', type_='unique')
    op.drop_index(op.f('ix_entry_inventory_inventory_id'), table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    # ### end Alembic commands ###
