"""Initial migration

Revision ID: 372e0f2fd2d5
Revises: 87e0c29b44a7
Create Date: 2025-04-03 01:17:10.094238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372e0f2fd2d5'
down_revision: Union[str, None] = '87e0c29b44a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index(op.f('ix_entry_inventory_inventory_id'), 'entry_inventory', ['inventory_id'], unique=True)
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index(op.f('ix_entry_inventory_product_id'), 'entry_inventory', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_inventory_product_id'), table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=False)
    op.drop_index(op.f('ix_entry_inventory_inventory_id'), table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    # ### end Alembic commands ###
