"""change datatype int to str

Revision ID: 38c68ea11356
Revises: 6d80998eb28f
Create Date: 2025-04-08 08:55:14.596965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c68ea11356'
down_revision: Union[str, None] = '6d80998eb28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index(op.f('ix_entry_inventory_inventory_id'), 'entry_inventory', ['inventory_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_inventory_inventory_id'), table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    # ### end Alembic commands ###
