"""initial migration

Revision ID: 4ad84187815c
Revises: 
Create Date: 2025-04-12 14:18:14.695563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad84187815c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assign_to', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=False),
    sa.Column('sno', sa.String(), nullable=True),
    sa.Column('zone_activity', sa.String(), nullable=True),
    sa.Column('inventory_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('inventory_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('purpose_reason', sa.String(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('assign_by', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('assignment_return_date', sa.Date(), nullable=True),
    sa.Column('assignment_barcode', sa.String(), nullable=True),
    sa.Column('assignment_barcode_unique_code', sa.String(), nullable=True),
    sa.Column('assignment_barcode_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_name', 'assignment_inventory', ['employee_name'], unique=False)
    op.create_index('idx_employee_name_inventory', 'assignment_inventory', ['employee_name', 'inventory_id'], unique=False)
    op.create_index('idx_employee_name_project', 'assignment_inventory', ['employee_name', 'project_id'], unique=False)
    op.create_index('idx_employee_name_status', 'assignment_inventory', ['employee_name', 'status'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_assign_to'), 'assignment_inventory', ['assign_to'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_employee_name'), 'assignment_inventory', ['employee_name'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_inventory_id'), 'assignment_inventory', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_product_id'), 'assignment_inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_project_id'), 'assignment_inventory', ['project_id'], unique=False)
    op.create_table('entry_inventory',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('sno', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('inventory_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('total_quantity', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('purchase_dealer', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_amount', sa.String(), nullable=True),
    sa.Column('repair_quantity', sa.String(), nullable=True),
    sa.Column('repair_cost', sa.String(), nullable=True),
    sa.Column('on_rent', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('total_rent', sa.String(), nullable=True),
    sa.Column('rented_inventory_returned', sa.String(), nullable=False),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('on_event', sa.String(), nullable=False),
    sa.Column('in_office', sa.String(), nullable=False),
    sa.Column('in_warehouse', sa.String(), nullable=False),
    sa.Column('issued_qty', sa.String(), nullable=True),
    sa.Column('balance_qty', sa.String(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('bar_code', sa.String(), nullable=False),
    sa.Column('unique_code', sa.String(), nullable=False),
    sa.Column('barcode_image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('bar_code'),
    sa.UniqueConstraint('unique_code')
    )
    op.create_index('ix_entry_inventory_created_at', 'entry_inventory', ['created_at'], unique=False)
    op.create_index(op.f('ix_entry_inventory_inventory_id'), 'entry_inventory', ['inventory_id'], unique=True)
    op.create_index(op.f('ix_entry_inventory_product_id'), 'entry_inventory', ['product_id'], unique=True)
    op.create_index('ix_entry_inventory_updated_at', 'entry_inventory', ['updated_at'], unique=False)
    op.create_table('to_event_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('setup_date', sa.Date(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('project_barcode', sa.String(), nullable=True),
    sa.Column('project_barcode_unique_code', sa.String(), nullable=True),
    sa.Column('project_barcode_image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('ix_to_event_inventory_created_at', 'to_event_inventory', ['created_at'], unique=False)
    op.create_index('ix_to_event_inventory_project_id', 'to_event_inventory', ['project_id'], unique=False)
    op.create_index('ix_to_event_inventory_updated_at', 'to_event_inventory', ['updated_at'], unique=False)
    op.create_table('wastage_inventories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assign_to', sa.String(), nullable=True),
    sa.Column('sno', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('inventory_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('inventory_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('receive_date', sa.Date(), nullable=True),
    sa.Column('receive_by', sa.String(), nullable=True),
    sa.Column('check_status', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('zone_activity', sa.String(), nullable=True),
    sa.Column('wastage_barcode', sa.String(), nullable=True),
    sa.Column('wastage_barcode_unique_code', sa.String(), nullable=True),
    sa.Column('wastage_barcode_image_url', sa.String(), nullable=True),
    sa.Column('wastage_reason', sa.String(), nullable=True),
    sa.Column('wastage_date', sa.Date(), nullable=True),
    sa.Column('wastage_approved_by', sa.String(), nullable=True),
    sa.Column('wastage_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wastage_inventories_id'), 'wastage_inventories', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('zone_active', sa.String(), nullable=True),
    sa.Column('sno', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('per_unit_power', sa.String(), nullable=True),
    sa.Column('total_power', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('poc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['to_event_inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_wastage_inventories_id'), table_name='wastage_inventories')
    op.drop_table('wastage_inventories')
    op.drop_index('ix_to_event_inventory_updated_at', table_name='to_event_inventory')
    op.drop_index('ix_to_event_inventory_project_id', table_name='to_event_inventory')
    op.drop_index('ix_to_event_inventory_created_at', table_name='to_event_inventory')
    op.drop_table('to_event_inventory')
    op.drop_index('ix_entry_inventory_updated_at', table_name='entry_inventory')
    op.drop_index(op.f('ix_entry_inventory_product_id'), table_name='entry_inventory')
    op.drop_index(op.f('ix_entry_inventory_inventory_id'), table_name='entry_inventory')
    op.drop_index('ix_entry_inventory_created_at', table_name='entry_inventory')
    op.drop_table('entry_inventory')
    op.drop_index(op.f('ix_assignment_inventory_project_id'), table_name='assignment_inventory')
    op.drop_index(op.f('ix_assignment_inventory_product_id'), table_name='assignment_inventory')
    op.drop_index(op.f('ix_assignment_inventory_inventory_id'), table_name='assignment_inventory')
    op.drop_index(op.f('ix_assignment_inventory_employee_name'), table_name='assignment_inventory')
    op.drop_index(op.f('ix_assignment_inventory_assign_to'), table_name='assignment_inventory')
    op.drop_index('idx_employee_name_status', table_name='assignment_inventory')
    op.drop_index('idx_employee_name_project', table_name='assignment_inventory')
    op.drop_index('idx_employee_name_inventory', table_name='assignment_inventory')
    op.drop_index('idx_employee_name', table_name='assignment_inventory')
    op.drop_table('assignment_inventory')
    # ### end Alembic commands ###
