"""Add Assignment Inventory

Revision ID: 51f77e1bdfb8
Revises: 38c68ea11356
Create Date: 2025-04-10 01:14:26.510350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f77e1bdfb8'
down_revision: Union[str, None] = '38c68ea11356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assign_to', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=False),
    sa.Column('sno', sa.String(), nullable=True),
    sa.Column('zone_activity', sa.String(), nullable=True),
    sa.Column('inventory_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('inventory_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('purpose_reason', sa.String(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('assign_by', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('assignment_return_date', sa.Date(), nullable=True),
    sa.Column('assignment_barcode', sa.String(), nullable=True),
    sa.Column('assignment_barcode_unique_code', sa.String(), nullable=True),
    sa.Column('assignment_barcode_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_name', 'assignment_inventory', ['employee_name'], unique=False)
    op.create_index('idx_employee_name_inventory', 'assignment_inventory', ['employee_name', 'inventory_id'], unique=False)
    op.create_index('idx_employee_name_project', 'assignment_inventory', ['employee_name', 'project_id'], unique=False)
    op.create_index('idx_employee_name_status', 'assignment_inventory', ['employee_name', 'status'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_assign_to'), 'assignment_inventory', ['assign_to'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_employee_name'), 'assignment_inventory', ['employee_name'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_inventory_id'), 'assignment_inventory', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_product_id'), 'assignment_inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_assignment_inventory_project_id'), 'assignment_inventory', ['project_id'], unique=False)
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=True)
    op.drop_index(op.f('ix_assignment_inventory_project_id'), table_name='assignment_inventory')
    op.drop_index(op.f('ix_assignment_inventory_product_id'), table_name='assignment_inventory')
    op.drop_index(op.f('ix_assignment_inventory_inventory_id'), table_name='assignment_inventory')
    op.drop_index(op.f('ix_assignment_inventory_employee_name'), table_name='assignment_inventory')
    op.drop_index(op.f('ix_assignment_inventory_assign_to'), table_name='assignment_inventory')
    op.drop_index('idx_employee_name_status', table_name='assignment_inventory')
    op.drop_index('idx_employee_name_project', table_name='assignment_inventory')
    op.drop_index('idx_employee_name_inventory', table_name='assignment_inventory')
    op.drop_index('idx_employee_name', table_name='assignment_inventory')
    op.drop_table('assignment_inventory')
    # ### end Alembic commands ###
