"""Initial migration

Revision ID: 53f99c65b7c5
Revises: 372e0f2fd2d5
Create Date: 2025-04-03 10:28:42.829200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f99c65b7c5'
down_revision: Union[str, None] = '372e0f2fd2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry_inventory', 'on_rent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry_inventory', 'rented_inventory_returned',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry_inventory', 'on_event',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry_inventory', 'in_office',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry_inventory', 'in_warehouse',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=True)
    op.alter_column('entry_inventory', 'in_warehouse',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry_inventory', 'in_office',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry_inventory', 'on_event',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry_inventory', 'rented_inventory_returned',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry_inventory', 'on_rent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
