"""wastage migration 1

Revision ID: 5498b3f50cf6
Revises: 4ad84187815c
Create Date: 2025-04-12 14:54:41.525322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5498b3f50cf6'
down_revision: Union[str, None] = '4ad84187815c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wastage_inventories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assign_to', sa.String(), nullable=True),
    sa.Column('sno', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('inventory_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('inventory_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('receive_date', sa.Date(), nullable=True),
    sa.Column('receive_by', sa.String(), nullable=True),
    sa.Column('check_status', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('zone_activity', sa.String(), nullable=True),
    sa.Column('wastage_barcode', sa.String(), nullable=True),
    sa.Column('wastage_barcode_unique_code', sa.String(), nullable=True),
    sa.Column('wastage_barcode_image_url', sa.String(), nullable=True),
    sa.Column('wastage_reason', sa.String(), nullable=True),
    sa.Column('wastage_date', sa.Date(), nullable=True),
    sa.Column('wastage_approved_by', sa.String(), nullable=True),
    sa.Column('wastage_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wastage_inventories_id'), 'wastage_inventories', ['id'], unique=False)
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    op.create_unique_constraint(None, 'inventory_items', ['id'])
    op.create_unique_constraint(None, 'to_event_inventory', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'to_event_inventory', type_='unique')
    op.drop_constraint(None, 'inventory_items', type_='unique')
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=True)
    op.drop_index(op.f('ix_wastage_inventories_id'), table_name='wastage_inventories')
    op.drop_table('wastage_inventories')
    # ### end Alembic commands ###
