"""modify barcode url notnull

Revision ID: 598e44934856
Revises: 012d6b7a94e6
Create Date: 2025-04-05 16:55:40.588757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598e44934856'
down_revision: Union[str, None] = '012d6b7a94e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=False)
    op.drop_constraint('to_event_inventory_project_barcode_image_url_key', 'to_event_inventory', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('to_event_inventory_project_barcode_image_url_key', 'to_event_inventory', ['project_barcode_image_url'])
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=True)
    # ### end Alembic commands ###
