"""Transparent barcode

Revision ID: 5bddf08efbce
Revises: 53f99c65b7c5
Create Date: 2025-04-03 12:03:52.497162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bddf08efbce'
down_revision: Union[str, None] = '53f99c65b7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry_inventory', sa.Column('barcode_image_url', sa.String(), nullable=True))
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index(op.f('ix_entry_inventory_inventory_id'), 'entry_inventory', ['inventory_id'], unique=True)
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=True)
    op.drop_index(op.f('ix_entry_inventory_inventory_id'), table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    op.drop_column('entry_inventory', 'barcode_image_url')
    # ### end Alembic commands ###
