"""Initial migration

Revision ID: 87e0c29b44a7
Revises: d4d4269aa525
Create Date: 2025-04-03 01:08:49.077848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e0c29b44a7'
down_revision: Union[str, None] = 'd4d4269aa525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_sno', table_name='entry_inventory')
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=True)
    op.create_index('ix_entry_inventory_sno', 'entry_inventory', ['sno'], unique=False)
    # ### end Alembic commands ###
