"""rename Material to RecQty

Revision ID: d1fbd391039a
Revises: 7cbca0d455ee
Create Date: 2025-04-15 07:26:44.790181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fbd391039a'
down_revision: Union[str, None] = '7cbca0d455ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('RecQty', sa.String(), nullable=True))
    op.drop_column('inventory_items', 'material')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('material', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('inventory_items', 'RecQty')
    # ### end Alembic commands ###
