"""To-event-Migration

Revision ID: fd1edca75910
Revises: aacd7fe6e773
Create Date: 2025-04-04 07:29:37.586743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1edca75910'
down_revision: Union[str, None] = 'aacd7fe6e773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_event_inventory',
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('sno', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone_active', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('per_unit_power', sa.String(), nullable=True),
    sa.Column('total_power', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('poc', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('setup_date', sa.Date(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('project_barcode', sa.String(), nullable=False),
    sa.Column('project_barcode_unique_code', sa.String(), nullable=False),
    sa.Column('project_barcode_image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('project_barcode'),
    sa.UniqueConstraint('project_barcode_unique_code')
    )
    op.create_index('ix_to_event_inventory_created_at', 'to_event_inventory', ['created_at'], unique=False)
    op.create_index('ix_to_event_inventory_project_id', 'to_event_inventory', ['project_id'], unique=False)
    op.create_index('ix_to_event_inventory_updated_at', 'to_event_inventory', ['updated_at'], unique=False)
    op.drop_index('ix_entry_inventory_inventory_id', table_name='entry_inventory')
    op.create_index(op.f('ix_entry_inventory_inventory_id'), 'entry_inventory', ['inventory_id'], unique=True)
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index(op.f('ix_entry_inventory_product_id'), 'entry_inventory', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_inventory_product_id'), table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=False)
    op.drop_index(op.f('ix_entry_inventory_inventory_id'), table_name='entry_inventory')
    op.create_index('ix_entry_inventory_inventory_id', 'entry_inventory', ['inventory_id'], unique=False)
    op.drop_index('ix_to_event_inventory_updated_at', table_name='to_event_inventory')
    op.drop_index('ix_to_event_inventory_project_id', table_name='to_event_inventory')
    op.drop_index('ix_to_event_inventory_created_at', table_name='to_event_inventory')
    op.drop_table('to_event_inventory')
    # ### end Alembic commands ###
