"""Initial migration

Revision ID: 397df6fa3cfb
Revises: 
Create Date: 2025-05-24 06:37:34.619623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397df6fa3cfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_product_id', table_name='entry_inventory')
    op.create_index(op.f('ix_entry_inventory_product_id'), 'entry_inventory', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_inventory_product_id'), table_name='entry_inventory')
    op.create_index('ix_entry_inventory_product_id', 'entry_inventory', ['product_id'], unique=False)
    # ### end Alembic commands ###
