"""Remove ProjectID

Revision ID: 3fdf2a86aad9
Revises: 2f5e25957f9f
Create Date: 2025-04-01 14:01:23.642724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdf2a86aad9'
down_revision: Union[str, None] = '2f5e25957f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry_inventory', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry_inventory', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry_inventory', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('entry_inventory', 'updated_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_entry_inventory_created_at', 'entry_inventory', ['created_at'], unique=False)
    op.create_index('ix_entry_inventory_updated_at', 'entry_inventory', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entry_inventory_updated_at', table_name='entry_inventory')
    op.drop_index('ix_entry_inventory_created_at', table_name='entry_inventory')
    op.alter_column('entry_inventory', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('entry_inventory', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('entry_inventory', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry_inventory', 'uuid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
