"""Initial migration

Revision ID: eeaa53e3ee14
Revises: 51c040487e32
Create Date: 2025-04-01 08:40:04.175364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeaa53e3ee14'
down_revision: Union[str, None] = '51c040487e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_inventory',
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('sno', sa.String(), autoincrement=True, nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('inventory_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('total_quantity', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('purchase_dealer', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_amount', sa.Float(), nullable=True),
    sa.Column('repair_quantity', sa.String(), nullable=True),
    sa.Column('repair_cost', sa.Float(), nullable=True),
    sa.Column('on_rent', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('total_rent', sa.Float(), nullable=True),
    sa.Column('rented_inventory_returned', sa.String(), nullable=True),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('on_event', sa.String(), nullable=True),
    sa.Column('in_office', sa.String(), nullable=True),
    sa.Column('in_warehouse', sa.String(), nullable=True),
    sa.Column('issued_qty', sa.String(), nullable=True),
    sa.Column('balance_qty', sa.String(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_entry_inventory_inventory_id'), 'entry_inventory', ['inventory_id'], unique=True)
    op.create_index(op.f('ix_entry_inventory_product_id'), 'entry_inventory', ['product_id'], unique=True)
    op.create_index(op.f('ix_entry_inventory_sno'), 'entry_inventory', ['sno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_inventory_sno'), table_name='entry_inventory')
    op.drop_index(op.f('ix_entry_inventory_product_id'), table_name='entry_inventory')
    op.drop_index(op.f('ix_entry_inventory_inventory_id'), table_name='entry_inventory')
    op.drop_table('entry_inventory')
    # ### end Alembic commands ###
